server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

  #mybatis-plush配置
  mybatis-plus:
    type-aliases-package: com.jt.pojo
    mapper-locations: classpath:/mybatis/mappers/*.xml
    configuration:
      map-underscore-to-camel-case: true
  #引入日志信息
  logging:
    level:
      com.jt.mapper: debug

#  redis:
#    host: localhost
#    database: 0
#    port: 6379
#    jedis:
#      pool:
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#    timeout: 5000

#添加dubbo配制
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.15.129:2181?backup=192.168.15.129:2182,192.168.15.129:2183


# 配置swagger
swagger:
  basePackage: com.jt.controller
  title: 李伟豪のAPI
  description: fuck the bug
  version: V1.0